version: '3.8'
name: my-expenses
networks:
  db:
    driver: bridge
services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - './.db:/var/lib/mysql'
    environment:
      - MYSQL_DATABASE=my_expenses
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - db
  adminer:
    image: adminer:4
    restart: always
    ports:
      - 3307:8080
    environment:
      - ADMINER_DEFAULT=mysql
      - ADMINER_DESIGN=dracula
    depends_on:
      - db
    networks:
      - db
  app:
    image: amazoncorretto:17-alpine-jdk
    working_dir: /app
    command: ./mvnw spring-boot:run
    ports:
      - 9000:9000
    volumes:
      - '.:/app'
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=my_expenses
      - DB_USER=root
      - DB_PASS=root
    depends_on:
      - db
    networks:
      - db
